version: "3.5"

services:
  namenode:
    image: adityap174/poc:hadoop-namenode-2.0.4-hadoop-3.2.0-java8
    container_name: namenode
    hostname: namenode
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-poc-env

  datanode:
    image: adityap174/poc:hadoop-datanode-2.0.4-hadoop-3.2.0-java8
    container_name: datanode
    hostname: datanode
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-poc-env

  zookeeper:
    image: adityap174/poc:zookeeper-2.0.4-hadoop-3.2.0-java8
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2818
      - 2888:2888
      - 3888:3888
    volumes:
      - zookeeper_conf:/opt/zookeeper/conf
      - zookeeper_tmp:/tmp/zookeeper
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-poc-env
  
  resourcemanager:
    image: adityap174/poc:hadoop-resourcemanager-2.0.4-hadoop-3.2.0-java8
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-poc-env

  nodemanager:
    image: adityap174/poc:hadoop-nodemanager-2.0.4-hadoop-3.2.0-java8
    container_name: nodemanager
    hostname: nodemanager
    ports:
      - 8042:8042
    volumes:
      - hadoop_nodemanager_docker:/var/lib/docker
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-poc-env
    privileged: true

  historyserver:
    image: adityap174/poc:hadoop-historyserver-2.0.4-hadoop-3.2.0-java8
    container_name: historyserver
    hostname: historyserver
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-poc-env
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hadoop_nodemanager_docker:
  zookeeper_conf:
  zookeeper_tmp:

networks:
  hadoop-poc-env:
   name: hadoop-poc-network



